export { normalizeDoc } from "./ast/normalize.js";
export type { Block, DocIR, InlineNode, RichText, TableCell } from "./ast/types.js";
export { loadConfig } from "./config/loadConfig.js";
export { loadTheme } from "./config/loadTheme.js";
export type { DocirConfig } from "./config/configSchema.js";
export { loadDoc } from "./loader/loadDoc.js";
export { blockSchema } from "./schema/blockSchemas.js";
export { docFileSchema, docSchema } from "./schema/docSchema.js";
export { themeSchema } from "./schema/themeSchema.js";
export type { DocirTheme } from "./schema/themeSchema.js";
export { renderBootstrapHtml, renderProject, validateDoc, validateProject } from "./core/index.js";
export type { LoadedProject, LoadProjectOptions, RenderProjectOptions, RenderProjectResult } from "./core/index.js";
export { renderMarkdownDocument } from "./renderer/markdown/index.js";
export { renderPlainCss, renderPlainDocument } from "./renderer/plain/index.js";
export { inlineNodeSchema, richTextSchema, tableCellSchema } from "./schema/inlineSchema.js";
export { migrateMarkdown, migrateMarkdownFile } from "./migration/markdown.js";
export type { MarkdownMigrationOptions, MarkdownMigrationResult, MarkdownMigrationWarning, MigrateMarkdownFileOptions } from "./migration/markdown.js";
